pilot/client.py, pilot/commands/auth/auth_commands.py, pilot/commands/main.py, pilot/config.py, pilot/profile.py, pilot/search.py, tests/unit/conftest.py, tests/unit/test_command_auth.py, tests/unit/test_profile.py
This also slightly changes logout behavior. Logging out now only revokes tokens to preserve custom profile info. 'logout --purge' has been added to clear all user info and transfer logs.
=> Added 'profile' command to check and modify user info

pilot/schemas/field_metadata.json, pilot/schemas/files.json, pilot/schemas/project_metadata.json, scripts/convert-to-project.py, scripts/ingest.py
Metadata changes
- Moves `previewbytes` to file attribute
- Makes `field_metadata` part of files object
- Adds `project-slug` to `project_metadata` to identify project
=> added script to convert previous metadata to new

README.rst, pilot/client.py, pilot/commands/project/project.py, pilot/commands/transfer/transfer_commands.py, pilot/globus_clients.py, pilot/project.py, pilot/schemas/project_metadata.json, pilot/search.py, requirements.txt, tests/unit/files/schemas/dataset/valid-minimal.json, tests/unit/files/schemas/dataset/valid-typical.json, tests/unit/files/schemas/dataset/valid-typical2.json, tests/unit/files/schemas/project_metadata/valid-minimal.json, tests/unit/files/schemas/project_metadata/valid-typical.json, tests/unit/test_client_data_utils.py, tests/unit/test_search.py
The final multi-project changes, minus tests. This covers:
* Fixed download
* Added `pilot project push` command for updating global projects list
* Removed metadata requirements
* Added `project-slug` to metadata
=> Multi project

pilot/client.py, pilot/commands/main.py, pilot/commands/transfer/transfer_commands.py, tests/unit/conftest.py
=> Added mkdir command.

pilot/client.py, pilot/commands/search/search_commands.py, tests/unit/test_client_path_resolution.py
=> Fixed '/' in 'get_path' to be relative inside project directory

pilot/commands/main.py, pilot/commands/project/project.py, pilot/commands/search/search_commands.py, pilot/project.py, tests/unit/test_command_search.py
Added both `edit project` and `delete project` for #41
=> Added 'pilot project delete` subcommand

pilot/commands/auth/auth_commands.py, pilot/commands/input_validation.py, pilot/commands/main.py, pilot/commands/project/project.py, pilot/project.py, tests/unit/test_command_main.py
* Added project subcommand descriptions
* When a project is not set, all non-project related subcommands can
be run without a warning being displayed
* The user is not bothered about updating projects if they are not
adding or deleting a project
=> Removed default projects and added User Experience tweaks

pilot/commands/auth/auth_commands.py, pilot/commands/transfer/transfer_commands.py, pilot/profile.py, tests/unit/test_command_auth.py
=> Fix when checking endpoint for the first time logging in user

pilot/commands/auth/auth_commands.py, pilot/commands/main.py, pilot/commands/project/project.py
Fixed `project` command reference and how `whoami` prints out.
=> minor fixes, project import, whoami

pilot/client.py, pilot/commands/search/delete.py, tests/unit/conftest.py, tests/unit/test_command_delete.py
Changes for #5 
I wanted to throw these changes in since we already have a 'delete' function in the pilot client. It turned out to be a little complex and not the '5 minute' problem I thought it was.
=> Delete file in addition to search record

pilot/commands/auth/auth_commands.py, pilot/commands/transfer/transfer_commands.py, pilot/config.py, pilot/exc.py, pilot/schemas/user_provided_metadata.json, pilot/search.py, tests/unit/files/schemas/user_provided_metadata/invalid-dc-all.json, tests/unit/files/schemas/user_provided_metadata/valid-dc-all.json, tests/unit/test_config.py
Added a few general fixes related to login, and extended the fields the user provide. All datacite fields can now be provided to override the defaults. This includes: publisher, publication date, subjects, dates, resource type and version.
=> Bug fixes and metadata improvements

pilot/analysis/__init__.py, pilot/commands/project/project.py, pilot/commands/transfer/transfer_commands.py, pilot/exc.py
Fixes for:
#61 -- Exception if project does not exist
#62 -- Analysis failing silently
#55 -- CSVs not being picked up properly by analytics
=> Fixed a few outstanding bugs

tests/integration/admin_test.sh
This adds a simple bash script to run through all of the pilot commands.
@rpwagner In retrospect, I'm not sure this is exactly what you had in mind, but it does offer a nice way to exercise all the commands. 
Example output: 
```
(pilot) $ ./admin_test.sh 
Running Admin Tests for Pilot Version 0.2.4.dev0
Initiating a fresh login...
You have been logged out.
You have been logged in.
Your Profile: 
Name:           Nickolaus Saint
Organization:   Globus
Identity:       nickolaussaint@globusid.org
Local Endpoint: My Work Laptop
Local Path:     ~/
Endpoint UUID:  bccfef42-9c19-11e9-8219-02b7a92d8e58
4 items to set. Type "help" for more information or "q" to quit.
Pick a title for your new project (My New Project)> 
Pick a short name (my-new-project)> 
Describe your new project (This project is …
```
=> Added admin test bash script

CHANGELOG.md, docs/user-guide.rst, meta.yaml, pilot/commands/auth/auth_commands.py, pilot/commands/main.py, pilot/commands/project/context.py, pilot/commands/transfer/analyze.py, pilot/commands/transfer/transfer_commands.py, pilot/context.py, pilot/version.py, requirements.txt, tests/unit/test_command_auth.py
These changes include build fixes for packaging the latest version on Conda. This took a bit longer than expected due to some problems found with the build, and some errors that would manifest on install (Confounding these are the fact that it takes AGES to complete a conda build, so you better get your meta.yaml file structured correctly or you're going to do a lot of waiting to fail and restart the build). fair-research-login 0.1.5 is now also on Conda (required for this build to complete), and installing with the command in the readme should now result in a seamless installation.
=> Build fixes

pilot/analysis/pandas.py, pilot/client.py, pilot/commands/project/project.py, pilot/commands/search/search_commands.py, pilot/search_parse.py, pilot/version.py, tests/unit/test_analyze.py, tests/unit/test_search_parse.py
These changes allow including HDF5 files in a pilot register or upload operation. 
These changes *should* have been the final changes for pilot, but in testing I found another bug related to multi-file operations. However, this completes the last feature on the list we have for Pilot.
=> Hdf5 multi file support

scripts/xpcs_metadata.py, scripts/xpcs_plots.py
Updates to xpcs plots:
* xpcs_metadata  -- creates a json file for metadata which can be uploaded via pilot
* xpcs_plots -- I changed the filenames outputted by the script. Names in the portal now correspond to the filenames of the images.
=> Xpcs scripts

pilot/client.py, pilot/commands/transfer/transfer_commands.py
I had a new metadata key cause ingests to fail without much explanation on what went wrong. I added some better hints as well as handling for top level PilotClientExceptions in the CLI.
=> Added better error handling for when ingest tasks fail

pilot/client.py, pilot/commands/main.py, pilot/commands/search/search_commands.py, pilot/commands/transfer/status_commands.py, pilot/commands/transfer/transfer_commands.py, pilot/exc.py, pilot/search_parse.py
This covers all the requested features here: #103 
Sample output:
```
(pilot) Firefly:pilot1-tools nick$ pilot upload meta.yaml /
Uploading meta.yaml using globus... 
The Globus Connect Personal endpoint 'My Work Laptop (30493e40-017a-11ea-9949-0a8c187e8c12)' is not currently connected to Globus
```
- - - -
```
(pilot) Firefly:pilot1-tools nick$ pilot describe A001_Aerogel_1mm_att3_Lq0_001_0001-1000
Title                /Users/nick/globus/aps/globus-automation/XPCS/data/A001_Aerogel_1mm_att3_Lq0_001_0001-1000.hdf
Authors              8-ID
Publisher            Automate
Subjects             XPCS
8-ID
Dates                Created:  Tuesday, Nov 05, 2019
Formats              image/png (24)
application/x-hdf (1)
Version              6
Combined Size        23 M
Description …
```
=> Requested features

pilot/analysis/__init__.py, pilot/analysis/image.py, requirements.txt
Pillow is the successor to the original PIL. I should have done this first.
```
"files": [
{
"sha256": "073a79185d8b77480e85617c8c2e2853e3d301e2af00bd9772bca6607715e239",
"md5": "1fb7ae66ad119d178ad4f87289041084",
"filename": "identifier-guidelines.png",
"url": "https://ebf55996-33bf-11e9-9fa4-0a06afd4a22e.e.globus.org/projects/mshukla-test4/identifier-guidelines.png",
"field_metadata": {
"name": "Image Metadata",
"width": 1460,
"height": 696,
"colorspace": "RGBA",
"format": "PNG",
"format_description": "Portable network graphics"
},
"mime_type": "image/png",
"length": 220923
}
],
```
=> Use Pillow instead of Wand

pilot/client.py, pilot/exc.py, pilot/search.py, pilot/search_parse.py
Added some needed features for XPCS, mainly:
* Allow metadata fields to be easily updated. This will allow for quick turnaround if anyone wants to add new fields for existing search records.
* Some better ingest safety, to allow for mistakes in ingest scripts.
* Squelched logging which is never used outside of pilot development.
=> Ingest improvements

pilot/analysis/__init__.py, pilot/client.py, pilot/commands/input_validation.py, pilot/commands/project/index.py, pilot/commands/project/project.py, pilot/commands/search/delete.py, pilot/config.py, pilot/context.py, pilot/exc.py, tests/unit/conftest.py, tests/unit/test_command_index.py, tests/unit/test_config.py, tests/unit/test_profile.py, tests/unit/test_transfer_log.py
These changes include the three main features above, including a bunch of bugfixes.
=> New features: configless pilot, cleaner project deletion, index-setup command
