globus/globus-pilot

docs/project-admin.rst, docs/reference.rst, docs/user-guide.rst, pilot/client.py, pilot/commands/input_validation.py, pilot/commands/path_utils.py, pilot/commands/project/project.py, pilot/commands/transfer/transfer_commands.py, pilot/project.py, pilot/schemas/project_metadata.json, pilot/search.py, tests/unit/conftest.py, tests/unit/test_client_path_resolution.py
Two major things come with this update:
* The project manifest is no longer held on petrel, instead it is ingested directly into search. 
* Adding new projects has been streamlined, and the master manifest is automatically updated after a new project has been added.
* Project 'paths' have been removed and automatically determined based on the 'project slug' in the 'projects' directory. 
This takes care of everything in #39 and #40
=> Project updates

pilot/commands/auth/auth_commands.py, pilot/commands/transfer/transfer_commands.py, pilot/profile.py
* Endpoint can be specified with `pilot profile --local-endpoint`
Changes for #42 
I went back and forth with this one over how careful the system should be when attempting to use endpoints that aren't local GCP endpoints. It can get weird if you set an endpoint on a remote system you're not ssh-ed into and still expect `pilot upload foo.txt` to work. I elected to keep it simple, and allow users to do this, although Globus will likely still accept the transfer then hang for a few days without actually completing it (`pilot status` will still show the transfer as active, just as Globus considers it 'active'). 
Validating the users chosen Globus local endpoint ended up being a bit complicated too. Again, keeping things simple, pilot simply exposes a CLI argument with `pilot profile …
=> Users can now set local endpoint

README.rst, docs/developer-guide.rst, docs/project-admin.rst, docs/user-guide.rst, meta.yaml
These changes update the docs and apply some fixes to the conda build script. 
A newer dry-run dev package is now up on Conda here: https://anaconda.org/nickolaussaint/pilot1-tools
I think I've worked out the kinks with the newest build. All it should need is the newest PRs and it should be good to go. 
Edit: It still seems to be pulling in more files than it should. I think it may be expecting a MANIFEST.in, and since it's not getting it, conda just throws in everything. The initial build was 2 gigs, now half an MB after removing extraneous (my uncommitted testing stuff) files.
=> Added docs, simplified readme, updated user-guide install, added build

pilot/commands/input_validation.py, pilot/commands/project/project.py, pilot/commands/search/search_commands.py
Fixes for #53 and a project decorator not being set correctly. The fix for #53 was due to the project not being explicitly passed when fetching the index, causing pilot to default on the 'current' project's search index.
Other fixes:
* Fixed bug when uploading data to project with 'public' access
* Fixed #54 
* Silenced transfer email when deleting project
=> Project fixes

pilot/commands/main.py, pilot/commands/project/project.py
There are still a mixture of functions referring to both `@project` and `@project_command`. There are some variables that use `project` which would technically overwrite the @project command, so I went ahead and switched everything to use `@project_command`. Using `@project` would probably be fine, but it's possible we could run into errors if we ever expected to call into that module multiple times during the lifetime of an invoked command (Maybe possible in testing).
=> Changed project decorator from 'project' to 'project_command'

pilot/analysis/__init__.py, pilot/analysis/tsv.py, pilot/commands/auth/auth_commands.py, pilot/commands/project/project.py, pilot/search.py, pilot/version.py, tests/unit/test_analyze.py
This adds a fix for #55 so pilot can upload arbitrary file types. Pilot won't necessarily analyze everything, but it now has a lookup table (lookup by mimetype) to determine what it should attempt to analyze, and what it should ignore (I played around a little with `import_module` for importing arbitrary analysis packages and running them, but that seemed to be overkill unless we want to allow users to have a flag or config that allows them to specify a function they want to run. For now, a simple lookup table should suit our needs just fine). 
Next up is getting images/pdfs/tsvs/csvs and raw text to display in the portal preview.
=> General analytics

pilot/commands/input_validation.py, pilot/commands/project/project.py, pilot/project.py
Marked [WIP], due to still waiting on access to the groups api so we can fetch the master subgroups list from Globus instead of tracking a separate list. 
Globus groups are now stored and loaded from the master project
manifest. This will allow us to add groups without doing a
pull request, and lays the groundwork for automatically fetching
groups from Globus.
=> [WIP] Dynamic groups

pilot/config.py
The big change in fair-research-login is switching to 'login-lists' to capture a users full login history. It turned out that the new storage mechanism we're using, configobj, does support storing lists of complex data, but getting it to do so is a little cumbersome. Although the specification lists information about `[[[__many__]]]` [sections](https://configobj.readthedocs.io/en/latest/configobj.html#repeated-sections) (lists of complex data), there doesn't seem to be documentation on storing data this way without defining a configspec. 
Since Pilot doesn't need to store more than one list of logins, these changes ensure it simply maintains a single one. It would be nice if native login supported this behavior as well, for times when storing multiple logins isn't necessary and the …
=> Added small fix for fair-research-login upgrade

CHANGELOG.md, pilot/client.py, pilot/commands/project/project.py, pilot/commands/transfer/transfer_commands.py, pilot/context.py, pilot/exc.py, pilot/search.py, pilot/version.py, tests/unit/conftest.py, tests/unit/test_client_data_utils.py, tests/unit/test_command_transfer.py, tests/unit/test_search.py
Moved all functionality from doing a `pilot upload foo.txt /` into the Pilot Client. It's now possible to do the same thing with: 
```
from pilot.client import PilotClient
pc = PilotClient()
pc.upload('foo.txt', '/')
```
Arguments are very similar to the CLI command, and allow passing a variety of arguments (update=True, dry_run=True, etc). Errors are handled by exceptions, all of which match the errors that are produced by the CLI. An example is here:
```
from pilot import client, exc
pc = client.PilotClient()
try:
pc.upload('foo.txt', '/', dry_run=True)
except exc.DryRun as dr:
print(dr)
print(dr.stats)
print(dr.CODE)
if dr.stats['record_exists'] is False:
pc.upload('foo.txt', '/')
except exc.PilotCodeException as pce:
print(pce)
print('Done!')
```
=> Moved upload functionality into Pilot Client

scripts/exalearn_tomogan_fix.py
This was a simple script to update metadata on the `exalearn` index, runnable on version 0.4.1 of pilot tools. This is probably a good replacement for the "exalearn" branch, as that code is based on a very old version of the pilot codebase. 
Runnable with:
`pilot context set exalearn`
`python scripts/exalearn_tomogan_fix.py`
=> Added exalearn script to `scripts`.

README.rst
Click may raise a nasty error if it doesn't find an encoding it
likes. This tells users how to fix the issue.
=> Added instructions for setting encodings on a user's system

pilot/commands/search/search_commands.py, tests/unit/test_command_search.py
One of the items in #103 
Example output:
```
(pilot) Firefly:pilot1-tools nick$ pilot list
Showing 5/5 of total results for "nick-testing"
Title                Data       Dataframe Rows   Column Size   Path
A001_Aerogel_1mm_att                                    32 M   A001_Aerogel_1mm_att6_Lq0_001_0001-1000
C017_Latex67nm_conc_                                    18 M   C017_Latex67nm_conc_att0_Lq0_001_0001-10000
B390_Dynamic_SMB_F_B                                    38 K   B390_Dynamic_SMB_F_BR2_Homo_Strain2.04mm_Ampl0.900mm_att0_Lq0_001_0001-5000
/Users/nick/globus/a                                    23 M   A001_Aerogel_1mm_att3_Lq0_001_0001-1000
meta.yaml                                               959    stuff/meta.yaml
Directories:
bar
stuff
```
- - - -
```
(pilot) …
```
=> The 'list' command now supports the path argument and lists directories

pilot/client.py, pilot/commands/search/delete.py, pilot/search_discovery.py, tests/unit/conftest.py, tests/unit/mocks.py, tests/unit/test_client_data_utils.py, tests/unit/test_client_path_resolution.py, tests/unit/test_search_discovery.py
**Note**: This is a single commit, but depends on #122 and #88. I'll keep it as a draft until those are merged. 
This in part addresses the issue to use universal identifiers (#123)
instead of short paths. If a user needs to download a file and
only has the full url, they can now call the native cli methods.
For example:
```
short_path = pc.get_short_path(url)
pc.download(short_path)
```
get_short_path() is pretty flexible, and `url` can be a:
* Globus Search subject
* Globus HTTP URL
* Globus URL (same as subject)
* full path in project
* shortpath
Each will raise an invalid project exception if some parts of the URL don't match, such as if the Globus endpoint does not match the endpoint configured for the project. The only exception above is `shortpath`, which is ambiguous and _must_ …
=> Added get_short_path() to address fundamental problem with Pilot scripting

pilot/client.py, pilot/exc.py
It was possible for the SDK to upload empty strings like so:
pc.upload('', '/')
The '' would be expanded to the entire base directory for the projcet
the user was working in, essentially making the whole project a
multi-file search entry.
The CLI wasn't affected, due to it automatically expanding paths before
calling into the SDK.
=> Added check to disallow uploading/ingesting illegal filenames

pilot/client.py
This will make pliot use the older style, prior to the newer style
coming out in a few days.
I started on switching Pilot over to the newer style, but it ended
up being a little more complex than I expected. Since we added
multi-file-entries, Pilot doesn't always get_subject when you ask
it to fetch a subject. Sometimes it needs to do a combination to
resolve whether you're talking about an exact search record, or a
file within a search record. The mechanisms for resolving entries
and files within entries are pretty well coupled to the older style.
=> Set version on post_search queries

pilot/commands/project/context.py
Wrong call was made to add context if it didn't exist. This didn't affect clients which had previously loaded the context and had it cached.
=> Fixed bug when setting new context that didn't previously exist

requirements.txt
We previously had a requirement for jsonschema < 3.0.0, which I believe was from tableschema. This caused problems with FuncX. Thankfully, tableschema updated their stuff so we can remove this restriction.
=> Upgrade jsonschema to >= 3.0.0

pilot/client.py, pilot/commands/auth/auth_commands.py, pilot/commands/main.py, pilot/commands/transfer/status_commands.py, pilot/config.py, tests/unit/conftest.py, tests/unit/test_client_data_utils.py, tests/unit/test_config.py, tests/unit/test_profile.py, tests/unit/test_transfer_log.py
@ryanchard These changes are for you! 
This should allow for setting two separate configs for different contexts. Alternate configs are settable both with env vars or by passing an optional filename to the PilotClient (env var takes precedence). This should handle both the case for running the Pilot CLI and for scripting, and should allow you to have dedicated configs for APS projects, where you want to ensure one particular context. 
Set config file by env var:
export PILOT_CONFIG="~/.pilot1-xpcs.cfg"
Set config file via scripting:
from pilot.client import PilotClient
pc = PilotClient(config_file='~/.pilot1-ssx.cfg')
=> Feature: Pilot config file configurable with env var or optional param

pilot/commands/project/project.py
Handy option to keep the empty shell of a project around after deleting all the data. Essentially allows us to 'wipe' projects and start over without needing to fill in the old project context.
=> Added --keep-context flag to pilot project delete command

pilot/commands/main.py, pilot/commands/project/index.py, pilot/context.py, tests/unit/mocks.py, tests/unit/test_command_index.py
Previously, 'context' was a hidden command to switch indices for pilot. Since pilot is now public, this has been changed to 'index' for clarity and made public.
=> Change context to index
